### ISSUE TITLE
crictl fails to create a pod when crio running with --uid-mappings and --gid-mappings

### ISSUE THREAD

**Issue by vikaschoudhary16** [kubernetes-sigs/cri-o#1929] opened 2018-11-26 11:28 UTC
**Description**
Running crio with id mappings:
` /usr/local/bin/crio --uid-mappings 0:100000:70000 --gid-mappings 0:100000:70000`
Now if i try to create a pod using `crictl`, following the [crio tutorial](https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md#run-pod-sandbox-with-config-file), like this:
```
$ crictl runp pod-config.json
```

I get this error message:
```
FATA[0000] run pod sandbox failed: rpc error: code = Unknown desc = container create failed: container_linux.go:337: starting container process caused "process_linux.go:403: container init caused \"rootfs_linux.go:147: setting rootfs as readonly caused \\\"operation not permitted\\\"\"" 
```

**UPDATE:**
Tried userns functionality with podman and it worked. Then i compared crio vs podman and found that podman does not set rootfs as ReadOnly, while crio does, https://github.com/kubernetes-sigs/cri-o/blob/master/server/sandbox_run_linux.go#L142. At least this explains why podman worked and crio dint.
Difference b/w crio and podman is deliberate or undesired inconsistency?

But if ID Mappings are not used on crio, all works fine.

**Output of `crio --version`:**

```
crio version 1.12.0-dev
commit: "58b6f760f64afcaadf80abd501a6eaae197778e0-dirty"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
local fedora 29

**Comment by giuseppe** [comment] 2018-11-27 11:07
this seems to be caused by newer versions of crictl (which possibly switched to default to readonly rootfs = true) and happens also without using uid/gid mappings.

It looks like this issue in runc: https://github.com/opencontainers/runc/issues/1247

For now, you could edit `/etc/containers/storage.conf` and be sure `mountopt` doesn't contain `nodev`.

We are seeing this problem now as we have switched to default to "nodev" and there was a change in containers/storage, recently inherited by CRI-O, to start honoring it

**Comment by rhatdan** [comment] 2018-11-27 17:35
But it also decreases the security....  :^(

**Comment by vikaschoudhary16** [comment] 2018-11-27 17:35
@giuseppe After Step 3 i.e pod running in the case where crio is running with uid-mapping, crictl fails to delete the same pod.

```
[root@fed-node ~]# crictl pods
POD ID              CREATED             STATE               NAME                NAMESPACE           ATTEMPT
bab80cde913a5       8 seconds ago       Ready               b44-nginx-sandbox   default             1
e66fad7006ec4       23 seconds ago      Ready               b3-nginx-sandbox    default             1
[root@fed-node ~]# crictl rmp bab80cde913a5
FATA[0000] removing the pod sandbox "bab80cde913a5" failed: rpc error: code = Unknown desc = failed to remove pod sandbox bab80cde913a54e518780fcefc6b2e6810815f956b824765deff19c82b46e911: remove /var/run/containers/storage/overlay-containers/bab80cde913a54e518780fcefc6b2e6810815f956b824765deff19c82b46e911/userdata/shm: device or resource busy
```

**Comment by mrunalp** [comment] 2018-11-28 04:46
@rhatdan We had to takeout nodev from mounts as well as it prevented buildah from creating overalyfs in mounts.

**Comment by giuseppe** [comment] 2018-11-28 09:18
> @giuseppe After Step 3 i.e pod running in the case where crio is running with uid-mapping, crictl fails to delete the same pod.

I think you need to use `stopp` first, then you can `rmp it

**Comment by rhatdan** [comment] 2018-11-28 20:52
Lets talk about this tomorrow.  Is this only failing when run with User Namespace?
Not sure how buildah would be related, since it should be getting a separate overlay volume mounted into the container that is running buildah,  Buildah should not be building over CRI-O overlayfs.

**Comment by vikaschoudhary16** [comment] 2018-12-02 17:03
@rhatdan in my testing, it was failing only with user namespaces.

**Comment by rhatdan** [comment] 2019-03-18 19:17
@giuseppe PTAL

**Comment by giuseppe** [comment] 2019-03-18 19:59
IIRC, we don't have nodev by default now and the other issue was related to not using `stopp`? 

@vikaschoudhary16 is there anything left to do here?

**Comment by rhatdan** [comment] 2019-03-18 20:09
Why would UID Mappings need Nodev by default?

**Comment by giuseppe** [comment] 2019-03-18 20:23
> Why would UID Mappings need Nodev by default?

it doesn't.  I think it was just the general setting to cause the issue

**Comment by giuseppe** [comment] 2019-03-19 08:17
I've tried and it works without "nodev", which is not the default; so I am closing this issue.

Please re-open if there is still something left to do

**Closed by giuseppe** 2019-03-19 08:17 UTC
