### ISSUE TITLE
Default pids_limit too low

### ISSUE THREAD

**Issue by steven-sheehy** [kubernetes-sigs/cri-o#1921] opened 2018-11-16 21:21 UTC
**Description**
For heavily mult-threaded workloads like databases, the default of 1024 for pids-limit is too low. This parameter controls not just the number of processes but also the amount of threads (since a thread is technically a process with shared memory). When installing CRI-O via the PPA, it comes pre-packaged with a crio.conf that defaults to 1024. Also CRI-O defaults internally to 1024 according to `crio --help | grep pids-limit`. 

I'm not sure what a good default is, but I set it to 64000 in my environment as that is what MongoDB recommended for nproc.

**Steps to reproduce the issue:**
1. Start CRI-O with defaults
2. Run the following test pod which kicks of 2048 threads:
```yaml
kubectl apply -f - <<EOF
apiVersion: v1
kind: Pod
metadata:
  name: pid-limit
spec:
  containers:
  - image: docker.io/ssheehy/pid-limit
    name: pid-limit
EOF
```

**Describe the results you received:**
Pod crashes repeatedly since it can't create threads past 1024

**Describe the results you expected:**
Pod continues to run and can create > 1024 threads.

**Additional information you deem important (e.g. issue happens only occasionally):**
Discussed in slack with @runcom and @mrunalp 

**Output of `crio --version`:**

```
crio version 1.11.9-dev
commit: ""
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 18.04
`ulimit -u` is 47931
Kubernetes v1.11.4

**Comment by cyphar** [comment] 2018-11-20 05:32
That's a bit of a worry. It means that containers under containerd can trivially fork-bomb the system.

**Comment by runcom** [comment] 2018-11-20 09:21
Right, that's the reason why (fork bomb) we are defaulting as low but give the possibility to users to tune it the way they need for their workloads.

**Comment by chrisnegus** [comment] 2018-11-20 19:45
I'd like to document this here: https://access.redhat.com/documentation/en-us/openshift_container_platform/3.11/html-single/cri-o_runtime/#configure-crio-use-crio-engine.  Questions: 1) Can pids_limit be set when the node is deployed or should you edit pids_limit in the crio.conf file on the node? 2) What guidance can we provide on when you need a higher limit (databases?)?  3) What can happen if the pids_limit is set too high or set to unlimited?

**Comment by cyphar** [comment] 2018-11-21 00:52
For the record, I think 1024 is **far** too small for a default. systemd did this for user slices and we saw (at SUSE) lots of regressions as a result. 4096 (the systemd default for services) is much more reasonable.

> 2) What guidance can we provide on when you need a higher limit (databases?)?

I would recommend testing-under-load the default limit (which hopefully will be updated to 4K), and doubling it if it's not enough. In general I would avoid having a limit which is larger than 16K (a single container shouldn't generally have 16K threads running -- 4K should be more than enough for most people).

> 3) What can happen if the pids_limit is set too high or set to unlimited?

If it's set to `max` (unlimited) then containers can trivially fork-bomb the entire system, even if you have strict memory and kernel memory limits set for the container. If it's set too high then containers can cause a PID shortage which might have an impact on other container processes (since the PID limit is global, and running lots of containers with high PID limits might result in temporary PID exhaustion depending on the workload).

**Comment by rhatdan** [comment] 2019-03-18 19:16
@steven-sheehy @cyphar I beleive this current default is 4k, closing.  Re-open if you disagree.

**Closed by rhatdan** 2019-03-18 19:16 UTC

**Comment by mtrmac** [comment] 2019-10-04 00:12
FWIW `config/config.go:DefaultPidsLimit` is 1024 on all branches at least since 1.10 up to, and including, `master`; I can’t see anything suggesting 4k.

**Comment by rhatdan** [comment] 2019-10-04 10:07
Yes you are right.  Should we increase it?  @mrunalp WDYT?

**Comment by mrunalp** [comment] 2019-10-04 10:43
Yeah sounds good. We had bumped it up for docker iirc.

**Comment by runcom** [comment] 2019-10-04 10:47
reason for not going to 4k was fork bomb, I remember we argued on that a lot and that's why we never changed it. It may be the case to change it now tho

**Comment by cyphar** [comment] 2019-10-04 10:56
Split the difference and make it 2K. :wink:  pidns shouldn't make a difference -- pids in a pidns still show up on the host and can still cause forkbombs.

**Comment by mnaser** [comment] 2019-10-28 01:19
This also really hurts running MySQL servers.  Is it okay to push up a patch to set it to 4096?

**Comment by rhatdan** [comment] 2019-10-28 13:13
@mnaser Can't you specifiy in the kubernetes yaml a higher pids_limit for the pod that is running MySQL server?

**Comment by mnaser** [comment] 2019-10-28 13:23
@rhatdan I've just did a bit of research and it seems that we can override the CRI-O value for the entire node:

https://github.com/kubernetes/kubernetes/blob/887edd2273a688f3730244dc781b76b27003d005/cmd/kubelet/app/options/options.go#L527

Therefore, we can probably settle to setting that value for now in the `kubelet` args as an easier method than overriding the default `cri-o` configuration.
