### ISSUE TITLE
Cannot delete pods completely with clear containers

### ISSUE THREAD

**Issue by ddongchen** [kubernetes-sigs/cri-o#1279] opened 2018-01-22 11:00 UTC
**Description**

 I tested the cri-o with clear containers runtime and found the pod cannot be deleted completely.
**Steps to reproduce the issue:**
1. Using kubernetes to create the pod
[xxx]# ./cluster/kubectl.sh get pod
NAME       READY     STATUS    RESTARTS   AGE
pod-test   1/1       Running   0          11m

we can also see from crictl:
[xxx]# crictl pods
PODSANDBOX ID       CREATED             STATE               NAME                NAMESPACE           ATTEMPT
17cd228356cf7       11 minutes ago      SANDBOX_READY       pod-test            default             0
[xxx]# crictl ps -a
CONTAINER ID        IMAGE                                     CREATED             STATE               NAME                ATTEMPT
9c25758ceb0a3      xxx  9 minutes ago       CONTAINER_RUNNING   pod-t               0

2. Deleting the pod from kubernetes:
[xxx]# ./cluster/kubectl.sh delete pod pod-test
pod "pod-test" deleted
[xxx]# ./cluster/kubectl.sh get pod
No resources found.

The pod is deleted from kubernetes successfully, while in fact, the pod is in "NotReady" state.
[xxx]# crictl pods
PODSANDBOX ID       CREATED             STATE               NAME                NAMESPACE           ATTEMPT
17cd228356cf7       14 minutes ago      **SANDBOX_NOTREADY**    pod-test            default             0
[xxx]# crictl ps -a
CONTAINER ID        IMAGE               CREATED             STATE               NAME                ATTEMPT

We delete the pod using "criclt", and failed.
[xxx]# crictl rmp 17c
FATA[0005] removing the pod sandbox failed: rpc error: code = Unknown desc = failed to delete container k8s_POD_pod-test_default_08acddcb-ff60-11e7-b62e-f0921cee3497_0 in pod sandbox 17cd228356cf7b872d316a5b2e0f0f4dccc0981646b80bcd919ff7380c186014: `/usr/bin/cc-runtime delete --force 17cd228356cf7b872d316a5b2e0f0f4dccc0981646b80bcd919ff7380c186014` failed: failed to connect to proxy after 5s: dial unix /run/virtcontainers/pods/17cd228356cf7b872d316a5b2e0f0f4dccc0981646b80bcd919ff7380c186014/proxy.sock: connect: connection refused
  (exit status 1) 

3. if we just use "crictl" to stop the pod, it's successful.
[xxx]# crictl pods
PODSANDBOX ID       CREATED             STATE               NAME                NAMESPACE           ATTEMPT
08182b3a31ad9       2 minutes ago       SANDBOX_READY       pod-test            default             0
[xxx]# crictl ps -a
CONTAINER ID        IMAGE                                     CREATED             STATE               NAME                ATTEMPT
bb65bbe26e757       xx   9 seconds ago       CONTAINER_RUNNING   pod-t               0
[xxx]# crictl stop bb65
bb65
[xxx]# crictl rm bb65
bb65
[xxx]# crictl stopp 0818
Stopped sandbox 0818
[xxx]# crictl rmp 0818
Removed sandbox 0818
[xxx]# crictl pods
PODSANDBOX ID       CREATED             STATE               NAME                NAMESPACE           ATTEMPT

I check the log from "crio" daemon, there is not so much differences. While i check the runtime log, i found the differences:
(1) When using "crictl", the last step is to destroy vm, while the cri-o does not have these cmd:
Jan 22 16:23:19  cc-proxy[17435]: time="2018-01-22T16:23:19.245629005+08:00" level=info msg="hyper(cmd=\\\"**destroypod**\\\", data=\\\"\\\")" client=13 name=cc-proxy pid=17435 source=proxy
.....
Jan 22 16:23:19  cc-runtime[18637]: time="2018-01-22T16:23:19+08:00" level=info msg="**Stopping VM**" 
......
time="2018-01-22T16:23:19.382775035+08:00" level=info msg="**UnregisterVM**()" client=14 name=cc-proxy pid=17435 source=proxy

(2) I found there is "stopping and stopped shims", while in cri-o, i just not found "stopped shims"
Jan 22 16:23:19  cc-runtime[18637]: time="2018-01-22T16:23:19+08:00" level=info msg="Stopping shim" shim-pid=17473 source=virtcontainers subsystem=shim
Jan 22 16:23:19 d cc-runtime[18637]: time="2018-01-22T16:23:19+08:00" level=info msg="**Stopped shims**" pod-id=5de6e8195caf73c1e9691a1d1503e1b40f211b873694aaa538a30eb1fb103662 shim-count=1 source=virtcontainers subsystem=pod

I'm not sure if the issue should be cri-o or clear containers. just firstly put it here.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

[xxx]# crictl --version
crictl version 1.0.0-alpha.0
the kubernetes is "release-1.9"
```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by runcom** [comment] 2018-01-22 11:28
@sameo PTAL

**Comment by sameo** [comment] 2018-01-24 14:11
@ddongchen this log:

```
 /usr/bin/cc-runtime delete --force 17cd228356cf7b872d316a5b2e0f0f4dccc0981646b80bcd919ff7380c186014 failed: failed to connect to proxy after 5s: dial unix /run/virtcontainers/pods/17cd228356cf7b872d316a5b2e0f0f4dccc0981646b80bcd919ff7380c186014/proxy.sock: connect: connection refused
```

seems to indicate that this is a Clear Containers issue. The pod proxy is dead, while cri-o believes the sandbox is still alive.

Could you please open an issue at github.com/clearcontainers/runtime with the entire CRI-O and runtime logs when trying to delete the pod?

Also, is that 100% reproducible? (I hope it is...)

**Comment by ddongchen** [comment] 2018-01-25 01:33
@sameo Yes, it's 100% reproduced on my local machine. 

I'll open another issue for the github.com/clearcontainers. 

I also observed the log "connection refused", what puzzled me most is that why "crictl" works well, while kubernetes cannot delete pod completely using "cri-o".

**Comment by rhatdan** [comment] 2018-03-16 18:31
@ddongchen @sameo Is this still an issue?

**Comment by umohnani8** [comment] 2019-03-04 19:27
@ddongchen @sameo is this still an issue?

**Comment by rhatdan** [comment] 2019-03-18 19:28
Closing since this is a year old.

**Closed by rhatdan** 2019-03-18 19:28 UTC

**Comment by carldanley** [comment] 2019-03-22 19:24
@rhatdan Sorry to bring it back up - just ran into this issue myself:

```
root@k8s-master-01:/etc/kubernetes# crictl pods
POD ID              CREATED             STATE               NAME                                       NAMESPACE           ATTEMPT
7494df16eb57b       41 minutes ago      Ready               coredns-86c58d9df4-phlqc                   kube-system         0
443c57e280ff2       41 minutes ago      Ready               calico-kube-controllers-644fcf8fbf-k6b9g   kube-system         0
02935a1675edd       41 minutes ago      Ready               coredns-86c58d9df4-t6lbw                   kube-system         0
root@k8s-master-01:/etc/kubernetes# crictl ps -a
CONTAINER ID        IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID
root@k8s-master-01:/etc/kubernetes# crictl rmp 02935a1675edd
FATA[0000] removing the pod sandbox "02935a1675edd" failed: rpc error: code = Unknown desc = sandbox container "02935a1675edd398ee6332e6006853b40a148b41d5c79fb143b74cb0be0a946b" is not fully stopped
```

**Comment by carldanley** [comment] 2019-03-22 20:04
I just restarted the host and the state changed from `Ready` to `NotReady` and I was able to delete the pod. Prior to that, it was just dangling and I wasn't able to delete the pod via any subset of commands.
