### ISSUE TITLE
Removing pod sandbox fails due to .../userdata/shm: device or resource busy

### ISSUE THREAD

**Issue by adelton** [kubernetes-sigs/cri-o#1453] opened 2018-03-14 15:58 UTC
**Description**

I create pod sandbox and I remove it right away. The removal fails.

**Steps to reproduce the issue:**
1. Have `podsandbox-config.json` file with content

```
{
    "metadata": {
        "name": "test-sandbox",
        "namespace": "default",
        "attempt": 1,
        "uid": "somerandomuid"
    },
    "linux": {
    }
}
```

2. Run `crictl runp podsandbox-config.json | xargs crictl rmp`

**Describe the results you received:**

```
FATA[0000] removing the pod sandbox "1bf62f11be134c6793628db4e75d65b93b9499c2d64fcf172a9c8b70b6f4bab3" failed: rpc error: code = Unknown desc = failed to remove pod sandbox 1bf62f11be134c6793628db4e75d65b93b9499c2d64fcf172a9c8b70b6f4bab3: remove /var/run/containers/storage/overlay-containers/1bf62f11be134c6793628db4e75d65b93b9499c2d64fcf172a9c8b70b6f4bab3/userdata/shm: device or resource busy 
```

**Describe the results you expected:**

```
Removed sandbox 1bf62f11be134c6793628db4e75d65b93b9499c2d64fcf172a9c8b70b6f4bab3
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `crio --version`:**

```
crio version 1.10.0-dev
commit: "712f3b8cf14cbbac298f3ccc020677ac2a65fa75"
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is with CRI-O built from master and `cri-tools` built from master (a6dd109ef238be53ab9a7a5c4642f8a1d4ba1bd6), with `crictl` configured with

```
# echo 'runtime-endpoint: unix:///var/run/crio/crio.sock' > /etc/crictl.yaml
```

**Comment by adelton** [comment] 2018-03-14 16:00
Even if I do the `crictl rmp` manually after a while and I wait until `crictl pods` shows `SANDBOX_READY`, I get the same failure.

However, rerunning the `crictl rmp` passes.

**Comment by adelton** [comment] 2018-03-14 16:03
However, the directory `/var/run/containers/storage/overlay-containers/.../userdata` stays around and an attempt to remove it fails with

```
# rm -rf /var/run/containers/storage/overlay-containers/1e68b5ede53e07bc3e4c226f769d74a57f1a89afc1be45926f02c9974f14b129/userdata
rm: cannot remove '/var/run/containers/storage/overlay-containers/1e68b5ede53e07bc3e4c226f769d74a57f1a89afc1be45926f02c9974f14b129/userdata/shm': Device or resource busy
```

After a while, there is ton of these `.../userdata/shm` mountpoints left around which does not seem healthy.

**Comment by rhatdan** [comment] 2018-03-14 16:05
We have cleaned this up on podmon.  It looks like a cleanup path is not happening if you just create the sandbox without creating a container, or does this leak happen both ways.

**Comment by adelton** [comment] 2018-03-14 16:22
I see this even if I create and start container in that pod.

I'm not sure I follow your reference to `podmon` ...

**Comment by rhatdan** [comment] 2018-03-14 17:06
The code looks correct.  But hard to say.

In sandbox_stop.go
```
	// unmount the shm for the pod
	if sb.ShmPath() != "/dev/shm" {
		// we got namespaces in the form of
		// /var/run/containers/storage/overlay-containers/CID/userdata/shm
		// but /var/run on most system is symlinked to /run so we first resolve
		// the symlink and then try and see if it's mounted
		fp, err := symlink.FollowSymlinkInScope(sb.ShmPath(), "/")
		if err != nil {
			return nil, err
		}
		if mounted, err := mount.Mounted(fp); err == nil && mounted {
			if err := unix.Unmount(fp, unix.MNT_DETACH); err != nil {
				return nil, err
			}
		}
	}
```

**Comment by rhatdan** [comment] 2018-03-14 17:07
If we add debug to this code to see if the paths are right and then code is actually being executed.

**Comment by mrunalp** [comment] 2018-03-14 17:26
This could be due to the shm leaking into other mount namespace.
@adelton When you hit this failure, can you grep for that particular path in other processes?
grep path /proc/*/mountinfo

And then see get a list of those processes. 

Also, are you testing on RHEL or Fedora?

We can use oci-umount to prevent leaks.

**Comment by adelton** [comment] 2018-03-14 17:33
That `grep` find the path in `/proc/*/mountinfo` in all processes in the system.

This is on Fedora 27 with kernel-4.15.7-300.fc27.x86_64.

**Comment by mrunalp** [comment] 2018-03-14 17:52
@adelton Can you enable oci-umount but with these paths in the config? https://github.com/projectatomic/oci-umount/commit/0ff3084750611396c5da2c16f4629f5c35de12d5

Also, you would need to make sure that this file is present:
```
[mrunalp@localhost cri-o]$ cat /usr/share/containers/oci/hooks.d/oci-umount.json 
{
    "hasbindmounts": true,
    "hook": "/usr/libexec/oci/hooks.d/oci-umount",
    "stage": [ "prestart" ]
}
```

And crio.conf has this setting:
```
hooks_dir_path = "/usr/share/containers/oci/hooks.d"
```

**Comment by dghubble** [comment] 2018-03-20 22:13
I can reproduce this issue as well on Fedora 27. I changed the `oci-umount.json` file as described (the other changes were already present) and `sudo crictl rms` started working.

**Comment by mrunalp** [comment] 2018-03-21 20:49
@dghubble Thanks for the report. Glad that oci-umount worked :)

**Comment by adelton** [comment] 2018-03-23 15:28
Is it expected that CRI-O functionality would depend on these external hooks that it does not ship?

**Comment by rhatdan** [comment] 2018-03-23 15:39
Does that mean we can close this.

**Comment by rhatdan** [comment] 2018-03-23 15:54
adelton, this is also required for docker to work correctly. Leaked mount points are a fact of life, this is not something we can control.  We should make oci-umount a requirement of the cri-o package though.

**Comment by adelton** [comment] 2018-04-04 09:54
Even if I install

```
# rpm -qf /usr/share/containers/oci/hooks.d/oci-umount.json
oci-umount-2.3.3-1.gite3c9055.fc27.x86_64
```

and have

```
# grep hooks_dir_path /etc/crio/crio.conf 
# hooks_dir_path is the oci hooks directory for automatically executed hooks
hooks_dir_path = "/usr/share/containers/oci/hooks.d"
```

the

```
crictl runp podsandbox-config.json | xargs crictl rmp
```

still fails, with CRI-O and `crictl` built from their masters.

**Comment by adelton** [comment] 2018-04-06 08:09
Hmm, when I append

```
/var/run/containers/storage/*
```

to `/etc/oci-umount.conf`, I no longer see the error. Having just the `/run/containers/storage/*` from https://github.com/projectatomic/oci-umount/commit/0ff3084750611396c5da2c16f4629f5c35de12d5 per https://github.com/kubernetes-incubator/cri-o/issues/1453#issuecomment-373115726 is not enough, in spite of the fact that

```
# ls -ld /var/run
lrwxrwxrwx. 1 root root 6 Apr  5 05:38 /var/run -> ../run
```

Should I file pull requests against https://github.com/projectatomic/oci-umount to also add the `/var/run/...` path? Or should something else (CRI-O?) be changed to actually use the `/run` and not `/var/run` location?

**Comment by adelton** [comment] 2018-04-06 08:28
It's even weirder. Thinks used to work with that `/var/run/containers/storage/*` for a while, namely when there were other pods still running on the machine.

However, when I remove all the pods and containers so that `crictl pods`, `crictl ps -a`, and `mount | grep userdata` don't list anything, running that

```
crictl runp podsandbox-config.json | xargs crictl rmp
```

fails again. The error message is

```
FATA[0000] removing the pod sandbox "921d9d5a5f2e1f87eb26d6620d3a91fd9bd0a69efea8ba56680581a8869b361e" failed: rpc error: code = Unknown desc = failed to remove pod sandbox 921d9d5a5f2e1f87eb26d6620d3a91fd9bd0a69efea8ba56680581a8869b361e: remove /var/run/containers/storage/overlay-containers/921d9d5a5f2e1f87eb26d6620d3a91fd9bd0a69efea8ba56680581a8869b361e/userdata/shm: device or resource busy 
```

and I see

```
# mount | grep userdata
shm on /run/containers/storage/overlay-containers/921d9d5a5f2e1f87eb26d6620d3a91fd9bd0a69efea8ba56680581a8869b361e/userdata/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,size=65536k)
```

(so it's (reported) mounted under `/run` while the error from `crictl` talks about `/var/run`).

When I run the

```
crictl runp podsandbox-config.json | xargs crictl rmp
```

again, it fails with

```
FATA[0000] removing the pod sandbox "31cbb20b282c737d19842b5cf1eb701497f22c394ed30fde4d88250a0126f14d" failed: rpc error: code = Unknown desc = failed to remove pod sandbox 31cbb20b282c737d19842b5cf1eb701497f22c394ed30fde4d88250a0126f14d: remove /var/run/containers/storage/overlay-containers/31cbb20b282c737d19842b5cf1eb701497f22c394ed30fde4d88250a0126f14d/userdata/shm: device or resource busy 
```

and I see

```
# mount | grep userdata
shm on /run/containers/storage/overlay-containers/31cbb20b282c737d19842b5cf1eb701497f22c394ed30fde4d88250a0126f14d/userdata/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,size=65536k)
```

-- the original `921d9d5a5f2e1f87eb26d6620d3a91fd9bd0a69efea8ba56680581a8869b361e` is now gone and `31cbb20b282c737d19842b5cf1eb701497f22c394ed30fde4d88250a0126f14d` stays around. So it looks like something (`oci-umount`?) is unmounting something, just not the mountpoint we'd care about.

**Comment by rhatdan** [comment] 2018-04-06 12:24
@rhvgoyal WDYT?
@adelton Open a PR for oci-umount for /var/run.

**Comment by rhvgoyal** [comment] 2018-04-06 18:41
So what is the problem? We are trying to remove a container/pod and that fails because associated mount point is busy? If shm is still mounted on, that directory removal will fail. So first thing is to figure out why this  shm is still mounted on.

**Comment by vikaschoudhary16** [comment] 2018-12-28 12:45
@adelton As @rhatdan mentioned, there is proper logic for unmounting in the sandbox-stop.go. And this unmounting logic is not there in the sandbox removal code flow. You faced this issue because you were trying to remove the sandbox without stopping it. runp -> stopp -> rmp is the expected call flow.

I think this issue can be closed.

**Comment by umohnani8** [comment] 2019-03-04 21:29
Logic should be `crictl stopp` then `crictl rmp`. Issue seems resolved, closing.

**Comment by adelton** [comment] 2019-03-05 09:38
I confirm that
```
crictl runp podsandbox-config.json | while read i ; do crictl stopp $i ; crictl rmp $i ; done
```
works with
```
cri-tools-1.0.0-2.alpha.0.git653cc8c.fc28.x86_64
cri-o-1.11.2-1.git3eac3b2.fc28.x86_64
runc-1.0.0-68.dev.git6635b4f.fc28.x86_64
```
But it still feels like `stopp` should be done automatically before the `rmp` -- after all, if I remove the sandbox, there is no longer any expectation that it should continue running, is there? Or there should be a `-f` option to force the removal, while refusing to remove sandbox which is not stopped.

**Closed** 2019-03-05 13:13 UTC
