### ISSUE TITLE
Storage/image handling should be configurable

### ISSUE THREAD

**Issue by cyphar** [kubernetes-sigs/cri-o#132] opened 2016-10-13 13:10 UTC
Specifically what I mean by this is that we need to make sure that we make it easy for constrained distributions to disable and enforce certain features. Namely:
- When the image code is merged, it's likely that we're going to be downloading images from the internet by default. However, it should be possible to **disable this entirely** using the configuration file. Certain deployments cannot start downloading images from the internet, and can only use the images packaged with the filesystem. This brings me to my second point ...
- It must be possible for the image code to take OCI bundles from the filesystem, and treat the filesystem as the source. This will allow for distributions to explicitly manage updating of images (as well as all of the advanced package management offered by distributions). I'm not sure how we should make the image:tag mapping work, but I think having some cache of images that distributions can put files into might work.

There's probably a few other things, but since that code hasn't been merged I haven't thought of them yet. I've just opened this so we can keep track of it.

**Comment by runcom** [comment] 2016-10-13 13:14
> When the image code is merged, it's likely that we're going to be downloading images from the internet by default. However, it should be possible to disable this entirely using the configuration file. Certain deployments cannot start downloading images from the internet, and can only use the images packaged with the filesystem. This brings me to my second point ...

would love to have this as well /cc @rhatdan 

> It must be possible for the image code to take OCI bundles from the filesystem, and treat the filesystem as the source. This will allow for distributions to explicitly manage updating of images (as well as all of the advanced package management offered by distributions). I'm not sure how we should make the image:tag mapping work, but I think having some cache of images that distributions can put files into might work.

this will likely be possible with https://github.com/kubernetes-incubator/cri-o/issues/28 since containers/image can get images from the filesystem as well (which could be on shared storage as well)

**Comment by rhatdan** [comment] 2016-10-13 13:14
I agree with this,  We need to be able to specify in the config which registries are available for pulling and pushing, of course default would be *.    We can do some of this potentially with the signing code in containers/image.

We have been working on a file system storage of images internally.  We should probably make the document public.  The idea we have is for network file system storage, but it should work fine with local storage.

**Comment by cyphar** [comment] 2016-12-20 12:45
I've had some pretty interesting ideas about distributing images through RPMs. Currently it only exists as an internal RFC document, but the general idea is that we generate RPMs for each blob with metadata tagged from the manifest and other sources in the image.

The reason I bring this up is that it might be possible for this to be transparent if `ocid` grows some sort of hook support, allowing you to specify a script that will pull an image for `umoci` and will then return a `containers/image` transport that can then be used to copy the image into `containers/storage`.

The cool thing is that with this hook functionality you could do `zypper in -y oci(opensuse/amd64:42.2)` and then return `oci:/var/lib/oci:opensuse-amd64-42.2` from the hook which will then be used as the transport for `containers/image`. This would then allow for `rpm` to manage updates of container image updates (though there's a question about how the pulling policy in k8s will interact with this).

WDYT @runcom @rhatdan @mrunalp ?

**Comment by rhatdan** [comment] 2017-07-11 21:27
@runcom Is this a duplicate of your --block-registry issue?

**Comment by runcom** [comment] 2017-07-12 10:49
@rhatdan half and half. This is also about ways to tell c/storage to _pull_ from the fs.

**Comment by rhatdan** [comment] 2018-03-16 18:10
@runcom @cyphar Where are we on this issue?

**Comment by rhatdan** [comment] 2019-03-08 18:51
Since this is several years old and nobody is working on it, I will close.  Reopen if someone wants to work on it.

**Closed by rhatdan** 2019-03-08 18:51 UTC
